---
- name: install ufw
  become: true
  apt:
    name: "ufw"

- name: setup open ports
  become: true
  ufw:
    rule: "allow"
    port: "{{ item }}"
  with_items: "{{ open_ports }}"

- name: set default policy to deny and start firewall
  become: true
  ufw:
    policy: "deny"
    state: "enabled"
