---
- name: Install mosquitto
  package: name={{ item }} state=present
  with_items:
  - mosquitto
  tags: [mosquitto]

- name: install mosquitto.conf file
  template:
    src: mosquitto.conf.j2
    dest: "/etc/mosquitto/mosquitto.conf"
    owner: root
    group: root
    mode: 0644

- name: install passwd file
  template:
    src: passwd.j2
    dest: "/etc/mosquitto/passwd"
    owner: root
    group: root
    mode: 0644

- name: Enable and start mosquitto
  sudo: yes
  service: >
    name=mosquitto
    enabled=true
    state=started
  tags: [mosquitto]
