- name: install required packages
  package: name={{ item }} state=present
  with_items:
  - influxdb

- name: install required python 3 modules (pre-install)
  pip: name={{ item }} extra_args="--upgrade" executable=pip
  with_items:
  - requests
  - influxdb

- name: start influxdb
  systemd:
    name: influxdb
    daemon_reload: yes
    enabled: yes
    state: started
#
#- name: Create influxdb database using custom credentials
#  influxdb_database:
#      hostname: "127.0.0.1"
#      username: "home-assistant"
#      password: "{{ influxdb_password }}"
#      database_name: "home_assistant"
#      ssl: yes
#      validate_certs: yes