# This file is part of the Home Assistant role.
#
# Copyright (c) 2015-2017 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under MIT. All rights reserved.
#
---
- name: install required packages
  package: name={{ item }} state=present
  with_items:
  - python3-pip
  - python3-dev
  - gcc
  - libudev-dev
  - vim

- name: create user
  user: name={{ ha_user }}
        comment="Home Assistant"
        createhome=no
        system=yes
        shell="/sbin/nologin"
        groups=ha,dialout

- name: create directory
  file: path={{ ha_conf_dir }} state=directory mode=02775 owner={{ ha_user }} group={{ ha_user }}
